export const tricksData = [
    // ======= 1. 皿技 =======
    { id: 1, name: "大皿 (Big cup)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: true },
    { id: 2, name: "小皿 (Small cup)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: true },
    { id: 3, name: "中皿 (Base(Bottom) cup)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: true },
    { id: 4, name: "蠟燭 (Candlestick)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 5, name: "企鵝中皿 (Penguin Catch)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 6, name: "野球 (Baseball bat)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 7, name: "蹦級 (Bungee)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 8, name: "彈腿大皿 (Knee bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 9, name: "彈手大皿 (Arm bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 10, name: "彈衣服大皿 (Clothe bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 11, name: "彈珠大皿 (Ken bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 12, name: "離心轉 (Centrifuge)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 13, name: "軌道 (Orbit)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 14, name: "燕子歸巢 (Swallow Return)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 15, name: "敲回大皿 (Clack/Tap back)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 16, name: "吸玉 (Catch cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 17, name: "大皿滑玉 (Big cup slide spike)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 18, name: "撈金魚 (Goldfish scooping)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 19, name: "繞大皿 (Wrap it up B)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 20, name: "丟球大皿 (Tama grip,Throw to big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 21, name: "茶壺 (Turntable)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 22, name: "逆茶壺 (Inward turntable)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 23, name: "正逆茶壺 (Two-way turntable)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 24, name: "轉筆 (Pencil spinning)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 25, name: "抓劍中皿 (Grap base cup)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 26, name: "空中飛人 (Trapeze)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 27, name: "漩渦中皿 (Swirl base cup)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 28, name: "劍頂滑中皿 (kenstick slide base cup)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 29, name: "神龍擺尾 (Rising Dragon)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 30, name: "正座中皿撈金魚 (Seiza base cup goldfish scooping)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 31, name: "皿上來回 (Mosikame)", category: "皿技", subcategory: "皿上來回", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 32, name: "皿上敲皿來回 (Tap mosikame)", category: "皿技", subcategory: "皿上來回", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 33, name: "大波小波 (oonamikonami)", category: "皿技", subcategory: "皿上來回", totalCount: 0, todayCount: 0, isUnlocked: false },
  
    // ======= 2. 劍技 =======
    { id: 34, name: "止劍 (Spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 35, name: "章魚燒 (Takoyaki)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 36, name: "竹蜻蜓 (Flying top)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 37, name: "陀螺 (Gyroscope)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 38, name: "企鵝止劍 (Penguin spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 39, name: "瓢蟲止劍 (Ladybug spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 40, name: "居合止劍 (Faster than gravity)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 41, name: "合掌居合止劍 (Gassho iai spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 42, name: "墜球止劍 (Drop spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 43, name: "燭光止劍 (Candlelight spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 44, name: "掛軸拋劍收 (Scroll trade spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 45, name: "平衡拋劍收 (Balance trade spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 46, name: "猛拉止劍 (Yank spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 47, name: "丟球大皿止劍 (Tama grip, Throw to big cup, Spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 48, name: "企鵝中皿止劍 (Penguin basecup spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 49, name: "劍頂 (Frying pan)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 50, name: "裏劍頂 (Inward frying Pan)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 51, name: "劍頂止劍 (Frying pan spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 52, name: "劍頂滑玉 (Slide spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 53, name: "裏劍頂滑玉 (Inward slide spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 54, name: "正逆劍頂滑玉 (Two-way slide spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 55, name: "神轎 (Mikoshi)", category: "劍技", subcategory: "劍身", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 56, name: "直升機 (Helicopter)", category: "劍技", subcategory: "劍身", totalCount: 0, todayCount: 0, isUnlocked: false },
  
    // ======= 3. 飛行球系 =======
    { id: 57, name: "飛行球 (Swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 58, name: "皿頂飛玉 (Inward swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 59, name: "企鵝飛行球 (Penguin swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 60, name: "小指飛行球 (Finger spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 61, name: "燭光飛行球 (Candlelight swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 62, name: "飛行蠟燭中皿轉止劍 (Swing candle base cup trade spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 63, name: "繞指飛行球 (Finger twine spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 64, name: "繞皿飛行球 (Wrap it up spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 65, name: "繞腳飛行球 (Drop step)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 66, name: "地球 (Earth turn)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 67, name: "逆地球 (Inward earth turn)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 68, name: "招財貓地球 (Lucky cat earth turn)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 69, name: "螺旋丸 (Flying top)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 70, name: "天中殺 (Downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 71, name: "裏天中殺 (Inward downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 72, name: "地獄車 (Downearth)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 73, name: "裏地獄車 (Inward downearth)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 74, name: "中皿殺 (Base cup downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 75, name: "飛行機,中皿殺 (Airplane, Base cup, Downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 76, name: "天地二段 (2 step downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 77, name: "神龍天中殺 (Dragon downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
  
    // ======= 4. 飛行機系 =======
    { id: 78, name: "飛行機 (Airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 79, name: "逆飛行機 (Inward airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 80, name: "一迴旋飛行機 (1 turn airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 81, name: "二迴旋飛行機 (2 turn airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 82, name: "企鵝飛行機 (Penguin airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 83, name: "翻玉飛行機 (Scramble airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 84, name: "蜜蜂飛行機 (Waggle airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 85, name: "托盤飛行機 (Palm airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 86, name: "滯空飛行機 (Airplane straight air)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 87, name: "滯空轉球飛行機 (Tama turn)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 88, name: "蒲公英 (Spinning)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 89, name: "墜劍飛行機 (Drop airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 90, name: "跳劍 (Jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 91, name: "逆跳劍 (Inward jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 92, name: "企鵝跳劍 (Penguin jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 93, name: "招財貓跳劍 (Lucky cat jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 94, name: "航線收 (Falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 95, name: "裏航線收 (Inward falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 96, name: "企鵝航線收 (Penguin catch falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 97, name: "大皿航線收 (Big cup falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 98, name: "大皿直落飛行機 (Big cup trade airplane)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 99, name: "宇宙飛船 (UFO)", category: "飛行機系", subcategory: "橫置(UFO)", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 100, name: "外宇宙飛船 (Outward UFO)", category: "飛行機系", subcategory: "橫置(UFO)", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 101, name: "回聲 (Echo)", category: "飛行機系", subcategory: "橫置(UFO)", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 102, name: "重力機 (Stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 103, name: "企鵝重力機 (Penguin stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 104, name: "一迴旋重力機 (1 turn stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 105, name: "逆一迴旋重力機 (Inward 1turn stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 106, name: "重力機快手收 (Stuntplane fasthand)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 107, name: "撈泥鰍 (Loach scooping)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 108, name: "劍球換持 (Trade)", category: "飛行機系", subcategory: "換持", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 109, name: "旋轉換持 (Roll trade)", category: "飛行機系", subcategory: "換持", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 110, name: "拍手換持 (Clap trade)", category: "飛行機系", subcategory: "換持", totalCount: 0, todayCount: 0, isUnlocked: false },
  
    // ======= 5. 靜止系 =======
    { id: 111, name: "燈台 (Lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 112, name: "燈台收 (Lighthouse in)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 113, name: "燈台抓劍收 (Lighthouse trade spike)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 114, name: "燈立 (Airplane trade lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 115, name: "跳燈 (Lighthouse flip)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 116, name: "一迴燈 (1 turn lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 117, name: "二迴燈 (2 turn lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 118, name: "離心燈 (Centrifuge lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 119, name: "燈台離心收 (Pressure lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 120, name: "幽靈燈 (Ghost lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 121, name: "敲皿旋轉燈 (Tap spin lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 122, name: "敲皿燈 (Tap lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 123, name: "一迴燈台抓劍收 (1 turn lighthouse trade spike)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 124, name: "一迴燈台離轉收 (1 turn lighthouse, trade kenflip spike)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 125, name: "漩渦燈台 (Whirlpools lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 126, name: "懶人燈台 (Lazy lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 127, name: "直拉敲燈收 (Straight up tap in)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 128, name: "船錨 (Anchor)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 129, name: "月面 (Lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 130, name: "一迴月 (1 turn lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 131, name: "逆月 (Inward lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 132, name: "夢幻月 (Dream lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 133, name: "月上月 (Jumping lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 134, name: "鶯 (Bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 135, name: "飛行鶯 (Swing bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 136, name: "裏飛行鶯 (Inward swing bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 137, name: "鶯收 (Bird, Spike)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 138, name: "鶯一迴收 (Bird, 1 turn spike)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 139, name: "鶯上鶯 (Lunar flip)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 140, name: "淘氣鶯 (Naughty bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 141, name: "極渡谷 (Bird over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 142, name: "飛行極渡谷 (Bird swing over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 143, name: "二段極渡谷 (Bird twise over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 144, name: "極渡嶺 (Bird over the mountain)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 145, name: "鶯皿往返 (Bird nod-off cup)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 146, name: "鶯,航線收 (Bird,Falling in)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 147, name: "裏鶯 (Underbird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 148, name: "飛行裏鶯 (Swing underbird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 149, name: "裏極渡谷 (Underbird over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 150, name: "聖母峰 (Everest)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 151, name: "止滑極意", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 152, name: "太陽極意", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 153, name: "中皿極意 (Handstall)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 154, name: "大皿極意 (Wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 155, name: "小皿極意 (Small wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 156, name: "三日月極意 (Crescent wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 157, name: "小皿三日月極意 (Small crescent wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 158, name: "竹馬 (stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 159, name: "一迴竹馬 (1 turn stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 160, name: "裏竹馬 (Inward stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 161, name: "夢幻竹馬 (Dream stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 162, name: "竹馬上竹馬 (Stilt flip)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 163, name: "渡竹馬 (Stilt over the valley)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 164, name: "戰斧 (Axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 165, name: "一迴戰斧 (1 turn axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 166, name: "直拉逆戰斧 (Inward axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 167, name: "一迴逆戰斧 (Inward 1 turn axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 168, name: "斧上斧 (Axe flip)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 169, name: "渡戰斧 (Axe over the valley)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
  
    // ======= 6. 轉拋敲 =======
    { id: 170, name: "離轉大皿止劍 (Kenflip big cup, Spike)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 171, name: "離轉止劍 (Kenflip spike)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 172, name: "地球離轉 (Whirlwind)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 173, name: "離轉飛行球 (Swing late spike)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 174, name: "離轉地獄車 (Downward Whirlwind)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 175, name: "離轉幽靈燈 (Kenflip ghost lighthouse )", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 176, name: "轉劍飛行球 (Gunslinger spike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 177, name: "轉劍裏飛行球 (Inward gunslinger spike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 178, name: "轉劍鶯 (Gunslinger bird)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 179, name: "轉劍地球 (Gunslinger Downearth)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 180, name: "轉劍天中殺 (Gunslinger downspike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 181, name: "轉劍地獄車 (Gunslinger downearth)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 182, name: "拇指轉劍天中殺 (Thumbslinger downspike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 183, name: "拇指轉劍地獄車 (Thumbslinger downearth)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 184, name: "槍手 (Gunman)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 185, name: "雜耍大皿 (Juggle big cup)", category: "轉拋敲", subcategory: "雜耍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 186, name: "雜耍止劍 (Juggle spike)", category: "轉拋敲", subcategory: "雜耍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 187, name: "雜耍鶯 (Juggle bird)", category: "轉拋敲", subcategory: "雜耍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 188, name: "敲停收 (Cushion in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 189, name: "敲收 (Tap in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 190, name: "敲劍尖收 (Spike tap in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 191, name: "敲底收 (Stank flip in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 192, name: "嬉皮敲收 (Hippie flip in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
  
    // ======= 7. 線技 =======
    { id: 193, name: "宇宙遊泳 (Space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 194, name: "?月殺法 (Moon circle)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 195, name: "稻妻宇宙遊泳 (2 turn space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 196, name: "扇風機 (Hand roll)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 197, name: "空氣鞭 (Air whip)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 198, name: "蝴蝶舞 (Butterfly space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 199, name: "老鷹舞 (Eagle space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 200, name: "紅鶴宇宙遊泳 (Flamingo space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 201, name: "轉身宇宙遊泳 (Turn around space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 202, name: "翻玉宇宙遊泳 (Scramble space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 203, name: "旭日飛行機 (Rising airplane)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 204, name: "雙節棍飛行機 (Nunchucks airplane)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 205, name: "暴風雨 (Gale drop)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 206, name: "提線止劍 (Hanging spike)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 207, name: "中皿提線止劍 (Baescup hanging spike)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 208, name: "提線雙手接 (Hanging catch with both hands)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 209, name: "提線拍手接 (Hanging clap catch)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 210, name: "提線兩倍拍手接 (Hanging double clap catch)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 211, name: "提線飛行球 (Hanging swing spike)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 212, name: "提線飛行機 (Hanging airplane)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 213, name: "提線一迴飛行機 (Hanging 1 turn airplane)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 214, name: "提線燈 (Hanging lighthout)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 215, name: "提線一迴燈 (Hanging 1 turn lighthout)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 216, name: "雙指掛線 (Hang V)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 217, name: "掛V飛行機 (Flying V, Airplane)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 218, name: "掛線卡皿 (Mount-hang)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 219, name: "冷凍披薩 (Cold pizza)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 220, name: "搖籃 (Cradle)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
  
    // ======= 8. 一周系 =======
    { id: 221, name: "町一周 (Around town)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 222, name: "市內一周 (Around city)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 223, name: "村一周 (Around village)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 224, name: "縣一周 (Around prefecture)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 225, name: "地方一周 (Around region)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 226, name: "亞洲一周 (Around Asia)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 227, name: "日本一周 (Around Japan)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 228, name: "街區一周 (Around the block)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 229, name: "世界一周 (Around the world)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 230, name: "宇宙一周 (Around universe)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 231, name: "歐洲一周 (Around Europ)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 232, name: "美國一周 (Around USA)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 233, name: "加拿大一周 (Around Canada)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 234, name: "北美一周 (Around North America)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 235, name: "奧林匹克一周 (Around olympic)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 236, name: "坦布里奇韋爾斯一周 (Around Tunbridge wells)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 237, name: "丹麥一周 (Around Danmark)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 238, name: "比利時一周 (Around Belgium)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 239, name: "航線一周 (Around falling in)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 240, name: "鶯一周 (Around bird)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 241, name: "裏鶯一周 (Around underbird)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 242, name: "銀河系一周 (Around galaxy)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 243, name: "神轎一周 (Around mikoshi)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 244, name: "皿胴一周 (Around the cup)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 245, name: "抓皿一周 (Around catch cup)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 246, name: "蠟燭皿一周 (Candle block)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 247, name: "極意一周 (Around stall)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 248, name: "歐洲極意 (Europ stall)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 249, name: "時鐘一周 (Around the clock)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 250, name: "雜耍一周 (Around juggle)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 251, name: "雜耍極意一周 (Around juggle stall)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 252, name: "離轉一周 (Around kenflip)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 253, name: "地球離轉一周 (Around whirlwind)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: 254, name: "浮生一周 (Around Fu-Sheng)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false }
  ];