// js/tricks-data.js
// 🎯 ID 格式已改為 "大分類序號_小分類序號_該小分類內流水號"（例如 1_1_1）。
// 新增招式時，只要接續在對應小分類最後面往下編號即可，不必更動其他招式的 ID，
// 也不會影響使用者雲端已儲存的舊資料（原本用純數字 id 當 key，改字串 id 後舊資料不會互相衝突）。
export const tricksData = [

    // ======= 1. 皿技 =======
    { id: "1_1_1", name: "大皿 (Big cup)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: true },
    { id: "1_1_2", name: "小皿 (Small cup)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: true },
    { id: "1_1_3", name: "中皿 (Base(Bottom) cup)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: true },
    { id: "1_1_4", name: "蠟燭 (Candlestick)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_1_5", name: "企鵝中皿 (Penguin Catch)", category: "皿技", subcategory: "基礎技", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_1", name: "野球 (Baseball bat)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_2", name: "蹦級 (Bungee)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_3", name: "彈腿大皿 (Knee bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_4", name: "彈手大皿 (Arm bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_5", name: "彈衣服大皿 (Clothe bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_6", name: "彈珠大皿 (Ken bounce big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_7", name: "離心轉 (Centrifuge)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_8", name: "軌道 (Orbit)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_9", name: "燕子歸巢 (Swallow Return)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_10", name: "敲回大皿 (Clack/Tap back)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_11", name: "吸玉 (Catch cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_12", name: "大皿滑玉 (Big cup slide spike)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_13", name: "撈金魚 (Goldfish scooping)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_14", name: "繞大皿 (Wrap it up B)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_2_15", name: "丟球大皿 (Tama grip,Throw to big cup)", category: "皿技", subcategory: "大皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_3_1", name: "茶壺 (Turntable)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_3_2", name: "逆茶壺 (Inward turntable)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_3_3", name: "正逆茶壺 (Two-way turntable)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_3_4", name: "轉筆 (Pencil spinning)", category: "皿技", subcategory: "茶壺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_4_1", name: "抓劍中皿 (Grap base cup)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_4_2", name: "空中飛人 (Trapeze)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_4_3", name: "漩渦中皿 (Swirl base cup)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_4_4", name: "劍頂滑中皿 (kenstick slide base cup)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_4_5", name: "神龍擺尾 (Rising Dragon)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_4_6", name: "正座中皿撈金魚 (Seiza base cup goldfish scooping)", category: "皿技", subcategory: "中皿", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_5_1", name: "皿上來回 (Mosikame)", category: "皿技", subcategory: "皿上來回", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_5_2", name: "皿上敲皿來回 (Tap mosikame)", category: "皿技", subcategory: "皿上來回", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "1_5_3", name: "大波小波 (oonamikonami)", category: "皿技", subcategory: "皿上來回", totalCount: 0, todayCount: 0, isUnlocked: false },

    // ======= 2. 劍技 =======
    { id: "2_1_1", name: "止劍 (Spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_2", name: "章魚燒 (Takoyaki)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_3", name: "竹蜻蜓 (Flying top)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_4", name: "陀螺 (Gyroscope)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_5", name: "企鵝止劍 (Penguin spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_6", name: "瓢蟲止劍 (Ladybug spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_7", name: "居合止劍 (Faster than gravity)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_8", name: "合掌居合止劍 (Gassho iai spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_9", name: "墜球止劍 (Drop spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_10", name: "燭光止劍 (Candlelight spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_11", name: "掛軸拋劍收 (Scroll trade spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_12", name: "平衡拋劍收 (Balance trade spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_13", name: "猛拉止劍 (Yank spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_14", name: "丟球大皿止劍 (Tama grip, Throw to big cup, Spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_1_15", name: "企鵝中皿止劍 (Penguin basecup spike)", category: "劍技", subcategory: "止劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_2_1", name: "劍頂 (Frying pan)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_2_2", name: "裏劍頂 (Inward frying Pan)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_2_3", name: "劍頂止劍 (Frying pan spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_2_4", name: "劍頂滑玉 (Slide spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_2_5", name: "裏劍頂滑玉 (Inward slide spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_2_6", name: "正逆劍頂滑玉 (Two-way slide spike)", category: "劍技", subcategory: "劍頂", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_3_1", name: "神轎 (Mikoshi)", category: "劍技", subcategory: "劍身", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "2_3_2", name: "直升機 (Helicopter)", category: "劍技", subcategory: "劍身", totalCount: 0, todayCount: 0, isUnlocked: false },

    // ======= 3. 飛行球系 =======
    { id: "3_1_1", name: "飛行球 (Swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_2", name: "皿頂飛玉 (Inward swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_3", name: "企鵝飛行球 (Penguin swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_4", name: "小指飛行球 (Finger spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_5", name: "燭光飛行球 (Candlelight swing spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_6", name: "飛行蠟燭中皿轉止劍 (Swing candle base cup trade spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_7", name: "繞指飛行球 (Finger twine spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_8", name: "繞皿飛行球 (Wrap it up spike)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_1_9", name: "繞腳飛行球 (Drop step)", category: "飛行球系", subcategory: "飛行球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_2_1", name: "地球 (Earth turn)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_2_2", name: "逆地球 (Inward earth turn)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_2_3", name: "招財貓地球 (Lucky cat earth turn)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_2_4", name: "螺旋丸 (Flying top)", category: "飛行球系", subcategory: "地球", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_1", name: "天中殺 (Downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_2", name: "裏天中殺 (Inward downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_3", name: "地獄車 (Downearth)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_4", name: "裏地獄車 (Inward downearth)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_5", name: "中皿殺 (Base cup downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_6", name: "飛行機,中皿殺 (Airplane, Base cup, Downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_7", name: "天地二段 (2 step downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "3_3_8", name: "神龍天中殺 (Dragon downspike)", category: "飛行球系", subcategory: "天中殺", totalCount: 0, todayCount: 0, isUnlocked: false },

    // ======= 4. 飛行機系 =======
    { id: "4_1_1", name: "飛行機 (Airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_2", name: "逆飛行機 (Inward airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_3", name: "一迴旋飛行機 (1 turn airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_4", name: "二迴旋飛行機 (2 turn airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_5", name: "企鵝飛行機 (Penguin airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_6", name: "翻玉飛行機 (Scramble airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_7", name: "蜜蜂飛行機 (Waggle airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_8", name: "托盤飛行機 (Palm airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_9", name: "滯空飛行機 (Airplane straight air)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_10", name: "滯空轉球飛行機 (Tama turn)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_11", name: "蒲公英 (Spinning)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_1_12", name: "墜劍飛行機 (Drop airplane)", category: "飛行機系", subcategory: "飛行機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_2_1", name: "跳劍 (Jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_2_2", name: "逆跳劍 (Inward jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_2_3", name: "企鵝跳劍 (Penguin jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_2_4", name: "招財貓跳劍 (Lucky cat jumping stick)", category: "飛行機系", subcategory: "跳劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_3_1", name: "航線收 (Falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_3_2", name: "裏航線收 (Inward falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_3_3", name: "企鵝航線收 (Penguin catch falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_3_4", name: "大皿航線收 (Big cup falling in)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_3_5", name: "大皿直落飛行機 (Big cup trade airplane)", category: "飛行機系", subcategory: "航線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_4_1", name: "宇宙飛船 (UFO)", category: "飛行機系", subcategory: "橫置(UFO)", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_4_2", name: "外宇宙飛船 (Outward UFO)", category: "飛行機系", subcategory: "橫置(UFO)", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_4_3", name: "回聲 (Echo)", category: "飛行機系", subcategory: "橫置(UFO)", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_5_1", name: "重力機 (Stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_5_2", name: "企鵝重力機 (Penguin stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_5_3", name: "一迴旋重力機 (1 turn stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_5_4", name: "逆一迴旋重力機 (Inward 1turn stuntplane)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_5_5", name: "重力機快手收 (Stuntplane fasthand)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_5_6", name: "撈泥鰍 (Loach scooping)", category: "飛行機系", subcategory: "重力機", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_6_1", name: "劍球換持 (Trade)", category: "飛行機系", subcategory: "換持", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_6_2", name: "旋轉換持 (Roll trade)", category: "飛行機系", subcategory: "換持", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "4_6_3", name: "拍手換持 (Clap trade)", category: "飛行機系", subcategory: "換持", totalCount: 0, todayCount: 0, isUnlocked: false },

    // ======= 5. 靜止系 =======
    { id: "5_1_1", name: "燈台 (Lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_2", name: "燈台收 (Lighthouse in)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_3", name: "燈台抓劍收 (Lighthouse trade spike)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_4", name: "燈立 (Airplane trade lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_5", name: "跳燈 (Lighthouse flip)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_6", name: "一迴燈 (1 turn lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_7", name: "二迴燈 (2 turn lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_8", name: "離心燈 (Centrifuge lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_9", name: "燈台離心收 (Pressure lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_10", name: "幽靈燈 (Ghost lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_11", name: "敲皿旋轉燈 (Tap spin lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_12", name: "敲皿燈 (Tap lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_13", name: "一迴燈台抓劍收 (1 turn lighthouse trade spike)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_14", name: "一迴燈台離轉收 (1 turn lighthouse, trade kenflip spike)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_15", name: "漩渦燈台 (Whirlpools lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_16", name: "懶人燈台 (Lazy lighthouse)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_17", name: "直拉敲燈收 (Straight up tap in)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_1_18", name: "船錨 (Anchor)", category: "靜止系", subcategory: "燈台", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_2_1", name: "月面 (Lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_2_2", name: "一迴月 (1 turn lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_2_3", name: "逆月 (Inward lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_2_4", name: "夢幻月 (Dream lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_2_5", name: "月上月 (Jumping lunar)", category: "靜止系", subcategory: "月面", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_1", name: "鶯 (Bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_2", name: "飛行鶯 (Swing bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_3", name: "裏飛行鶯 (Inward swing bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_4", name: "鶯收 (Bird, Spike)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_5", name: "鶯一迴收 (Bird, 1 turn spike)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_6", name: "鶯上鶯 (Lunar flip)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_7", name: "淘氣鶯 (Naughty bird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_8", name: "極渡谷 (Bird over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_9", name: "飛行極渡谷 (Bird swing over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_10", name: "二段極渡谷 (Bird twise over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_11", name: "極渡嶺 (Bird over the mountain)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_12", name: "鶯皿往返 (Bird nod-off cup)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_13", name: "鶯,航線收 (Bird,Falling in)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_14", name: "裏鶯 (Underbird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_15", name: "飛行裏鶯 (Swing underbird)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_16", name: "裏極渡谷 (Underbird over the valley)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_3_17", name: "聖母峰 (Everest)", category: "靜止系", subcategory: "鶯", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_4_1", name: "止滑極意", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_4_2", name: "太陽極意", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_4_3", name: "中皿極意 (Handstall)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_4_4", name: "大皿極意 (Wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_4_5", name: "小皿極意 (Small wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_4_6", name: "三日月極意 (Crescent wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_4_7", name: "小皿三日月極意 (Small crescent wing)", category: "靜止系", subcategory: "極意", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_5_1", name: "竹馬 (stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_5_2", name: "一迴竹馬 (1 turn stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_5_3", name: "裏竹馬 (Inward stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_5_4", name: "夢幻竹馬 (Dream stilt)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_5_5", name: "竹馬上竹馬 (Stilt flip)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_5_6", name: "渡竹馬 (Stilt over the valley)", category: "靜止系", subcategory: "竹馬", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_6_1", name: "戰斧 (Axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_6_2", name: "一迴戰斧 (1 turn axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_6_3", name: "直拉逆戰斧 (Inward axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_6_4", name: "一迴逆戰斧 (Inward 1 turn axe)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_6_5", name: "斧上斧 (Axe flip)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "5_6_6", name: "渡戰斧 (Axe over the valley)", category: "靜止系", subcategory: "戰斧", totalCount: 0, todayCount: 0, isUnlocked: false },

    // ======= 6. 轉拋敲 =======
    { id: "6_1_1", name: "離轉大皿止劍 (Kenflip big cup, Spike)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_1_2", name: "離轉止劍 (Kenflip spike)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_1_3", name: "地球離轉 (Whirlwind)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_1_4", name: "離轉飛行球 (Swing late spike)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_1_5", name: "離轉地獄車 (Downward Whirlwind)", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_1_6", name: "離轉幽靈燈 (Kenflip ghost lighthouse )", category: "轉拋敲", subcategory: "離轉", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_1", name: "轉劍飛行球 (Gunslinger spike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_2", name: "轉劍裏飛行球 (Inward gunslinger spike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_3", name: "轉劍鶯 (Gunslinger bird)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_4", name: "轉劍地球 (Gunslinger Downearth)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_5", name: "轉劍天中殺 (Gunslinger downspike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_6", name: "轉劍地獄車 (Gunslinger downearth)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_7", name: "拇指轉劍天中殺 (Thumbslinger downspike)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_8", name: "拇指轉劍地獄車 (Thumbslinger downearth)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_2_9", name: "槍手 (Gunman)", category: "轉拋敲", subcategory: "轉劍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_3_1", name: "雜耍大皿 (Juggle big cup)", category: "轉拋敲", subcategory: "雜耍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_3_2", name: "雜耍止劍 (Juggle spike)", category: "轉拋敲", subcategory: "雜耍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_3_3", name: "雜耍鶯 (Juggle bird)", category: "轉拋敲", subcategory: "雜耍", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_4_1", name: "敲停收 (Cushion in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_4_2", name: "敲收 (Tap in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_4_3", name: "敲劍尖收 (Spike tap in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_4_4", name: "敲底收 (Stank flip in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "6_4_5", name: "嬉皮敲收 (Hippie flip in)", category: "轉拋敲", subcategory: "敲", totalCount: 0, todayCount: 0, isUnlocked: false },

    // ======= 7. 線技 =======
    { id: "7_1_1", name: "宇宙遊泳 (Space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_2", name: "圓月殺法 (Moon circle)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_3", name: "稻妻宇宙遊泳 (2 turn space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_4", name: "扇風機 (Hand roll)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_5", name: "空氣鞭 (Air whip)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_6", name: "蝴蝶舞 (Butterfly space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_7", name: "老鷹舞 (Eagle space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_8", name: "紅鶴宇宙遊泳 (Flamingo space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_9", name: "轉身宇宙遊泳 (Turn around space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_10", name: "翻玉宇宙遊泳 (Scramble space walk)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_11", name: "旭日飛行機 (Rising airplane)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_12", name: "雙節棍飛行機 (Nunchucks airplane)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_1_13", name: "暴風雨 (Gale drop)", category: "線技", subcategory: "滯空", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_1", name: "提線止劍 (Hanging spike)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_2", name: "中皿提線止劍 (Baescup hanging spike)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_3", name: "提線雙手接 (Hanging catch with both hands)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_4", name: "提線拍手接 (Hanging clap catch)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_5", name: "提線兩倍拍手接 (Hanging double clap catch)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_6", name: "提線飛行球 (Hanging swing spike)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_7", name: "提線飛行機 (Hanging airplane)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_8", name: "提線一迴飛行機 (Hanging 1 turn airplane)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_9", name: "提線燈 (Hanging lighthout)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_2_10", name: "提線一迴燈 (Hanging 1 turn lighthout)", category: "線技", subcategory: "提線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_3_1", name: "雙指掛線 (Hang V)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_3_2", name: "掛V飛行機 (Flying V, Airplane)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_3_3", name: "掛線卡皿 (Mount-hang)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_3_4", name: "冷凍披薩 (Cold pizza)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "7_3_5", name: "搖籃 (Cradle)", category: "線技", subcategory: "操線", totalCount: 0, todayCount: 0, isUnlocked: false },

    // ======= 8. 一周系 =======
    { id: "8_1_1", name: "町一周 (Around town)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_2", name: "市內一周 (Around city)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_3", name: "村一周 (Around village)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_4", name: "縣一周 (Around prefecture)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_5", name: "地方一周 (Around region)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_6", name: "亞洲一周 (Around Asia)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_7", name: "日本一周 (Around Japan)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_8", name: "街區一周 (Around the block)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_9", name: "世界一周 (Around the world)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_10", name: "宇宙一周 (Around universe)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_11", name: "歐洲一周 (Around Europ)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_12", name: "美國一周 (Around USA)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_13", name: "加拿大一周 (Around Canada)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_14", name: "北美一周 (Around North America)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_15", name: "奧林匹克一周 (Around olympic)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_16", name: "坦布里奇韋爾斯一周 (Around Tunbridge wells)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_17", name: "丹麥一周 (Around Danmark)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_18", name: "比利時一周 (Around Belgium)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_19", name: "航線一周 (Around falling in)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_20", name: "鶯一周 (Around bird)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_21", name: "裏鶯一周 (Around underbird)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_22", name: "銀河系一周 (Around galaxy)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_23", name: "神轎一周 (Around mikoshi)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_24", name: "皿胴一周 (Around the cup)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_25", name: "抓皿一周 (Around catch cup)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_26", name: "蠟燭皿一周 (Candle block)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_27", name: "極意一周 (Around stall)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_28", name: "歐洲極意 (Europ stall)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_29", name: "時鐘一周 (Around the clock)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_30", name: "雜耍一周 (Around juggle)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_31", name: "雜耍極意一周 (Around juggle stall)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_32", name: "離轉一周 (Around kenflip)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_33", name: "地球離轉一周 (Around whirlwind)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
    { id: "8_1_34", name: "浮生一周 (Around Fu-Sheng)", category: "一周系", subcategory: "一周", totalCount: 0, todayCount: 0, isUnlocked: false },
];
